version: "3.8"

services:
  styletts2-api:
    image: 135808939327.dkr.ecr.us-east-1.amazonaws.com/styletts2-api
    # TODO: change to your own image name
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  seedvc-api:
    image: 135808939327.dkr.ecr.us-east-1.amazonaws.com/seed-vc-api
    # TODO: change to your own image name
    ports:
      - "8001:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  make-an-audio-api:
    image: 135808939327.dkr.ecr.us-east-1.amazonaws.com/make-an-audio-api
    # TODO: change to your own image name
    ports:
      - "8002:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]